import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/store/StoreProvider";
import { Toaster } from "@/components/ui/sonner";

import NextTopLoader from "nextjs-toploader";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader color="#ff0000" height={4} showSpinner={false}  />
        <Toaster closeButton position="top-center" />
        <SessionProvider>
          <StoreProvider>
            {children}
            <footer>Footer</footer>
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
